[package]
name = "tuff-adapter-cursor"
version.workspace = true
edition.workspace = true
description = "Cursor adapter for Tuff."
license.workspace = true
authors.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true

[dependencies]
tuff-core.workspace = true
tuff-hooks-spec.workspace = true
serde_json = "1.0.145"
